version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: face-rec:latest
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
